query listPrograms($filters: listProgramsInput) {
  listPrograms(filters: $filters) {
    programs{
        updated
        status
        pubId
        name
        followed
        feedback
        entity
        edited
        createdAt
        commented
        requests
    }
    total
  }
}
